"use client"
import "./globals.css";
import { Providers } from "./globalredux/provider";
// import Router from "next/router";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  return (
    <html lang="en">
      <body>

      <Providers>
        

        {children}
       

        
      </Providers>
      </body>
    </html>
  );
}
